/** Generated from the Geekbench 7 Mac benchmark family table.
 * Source capture and provenance are documented in processorCatalogue.ts.
 * Regenerate with scripts/generateMacCatalogue.ts; do not edit by hand.
 */
export const GENERATED_MAC_IDENTITIES = [
  {
    key: 'mac-mac-mini-2024-12c-cpu',
    displayName: 'Mac mini (2024) — Apple M4 Pro',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/mac-mini-2024-12c-cpu',
    processorPaths: [],
    macPaths: ['/macs/mac-mini-2024-12c-cpu'],
    aliases: ['Apple M4 Pro'],
    requiredConfiguration: {
      physicalCores: 12,
      gpuCores: 16,
    },
  },
  {
    key: 'mac-mac-mini-2024-14c-cpu',
    displayName: 'Mac mini (2024) — Apple M4 Pro',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/mac-mini-2024-14c-cpu',
    processorPaths: [],
    macPaths: ['/macs/mac-mini-2024-14c-cpu'],
    aliases: ['Apple M4 Pro'],
    requiredConfiguration: {
      physicalCores: 14,
      gpuCores: 20,
    },
  },
  {
    key: 'mac-mac-mini-2024-10c-cpu',
    displayName: 'Mac mini (2024) — Apple M4',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/mac-mini-2024-10c-cpu',
    processorPaths: [],
    macPaths: ['/macs/mac-mini-2024-10c-cpu'],
    aliases: ['Apple M4'],
    requiredConfiguration: {
      physicalCores: 10,
      gpuCores: 10,
    },
  },
  {
    key: 'mac-imac-24-inch-2024-10c-cpu',
    displayName: 'iMac (24-inch, 2024) — Apple M4',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/imac-24-inch-2024-10c-cpu',
    processorPaths: [],
    macPaths: ['/macs/imac-24-inch-2024-10c-cpu'],
    aliases: ['Apple M4'],
    requiredConfiguration: {
      physicalCores: 10,
      gpuCores: 10,
    },
  },
  {
    key: 'mac-imac-24-inch-2024-8c-cpu',
    displayName: 'iMac (24-inch, 2024) — Apple M4',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/imac-24-inch-2024-8c-cpu',
    processorPaths: [],
    macPaths: ['/macs/imac-24-inch-2024-8c-cpu'],
    aliases: ['Apple M4'],
    requiredConfiguration: {
      physicalCores: 8,
      gpuCores: 8,
    },
  },
  {
    key: 'mac-imac-24-inch-2023-8c-gpu',
    displayName: 'iMac (24-inch, 2023) — Apple M3',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/imac-24-inch-2023-8c-gpu',
    processorPaths: [],
    macPaths: ['/macs/imac-24-inch-2023-8c-gpu'],
    aliases: ['Apple M3'],
    requiredConfiguration: {
      physicalCores: 8,
      gpuCores: 8,
    },
  },
  {
    key: 'mac-imac-24-inch-2023-10c-gpu',
    displayName: 'iMac (24-inch, 2023) — Apple M3',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/imac-24-inch-2023-10c-gpu',
    processorPaths: [],
    macPaths: ['/macs/imac-24-inch-2023-10c-gpu'],
    aliases: ['Apple M3'],
    requiredConfiguration: {
      physicalCores: 8,
      gpuCores: 10,
    },
  },
  {
    key: 'mac-mac-mini-2023-10c-cpu',
    displayName: 'Mac mini (2023) — Apple M2 Pro',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/mac-mini-2023-10c-cpu',
    processorPaths: [],
    macPaths: ['/macs/mac-mini-2023-10c-cpu'],
    aliases: ['Apple M2 Pro'],
    requiredConfiguration: {
      physicalCores: 10,
      gpuCores: 16,
    },
  },
  {
    key: 'mac-mac-mini-2023-12c-cpu',
    displayName: 'Mac mini (2023) — Apple M2 Pro',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/mac-mini-2023-12c-cpu',
    processorPaths: [],
    macPaths: ['/macs/mac-mini-2023-12c-cpu'],
    aliases: ['Apple M2 Pro'],
    requiredConfiguration: {
      physicalCores: 12,
      gpuCores: 19,
    },
  },
  {
    key: 'mac-mac-mini-2023-8c-cpu',
    displayName: 'Mac mini (2023) — Apple M2',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/mac-mini-2023-8c-cpu',
    processorPaths: [],
    macPaths: ['/macs/mac-mini-2023-8c-cpu'],
    aliases: ['Apple M2'],
    requiredConfiguration: {
      physicalCores: 8,
      gpuCores: 10,
    },
  },
  {
    key: 'mac-mac-studio-apple-m1-ultra',
    displayName: 'Mac Studio — Apple M1 Ultra',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/mac-studio-apple-m1-ultra',
    processorPaths: [],
    macPaths: ['/macs/mac-studio-apple-m1-ultra'],
    aliases: ['Apple M1 Ultra'],
    requiredConfiguration: {
      physicalCores: 20,
    },
  },
  {
    key: 'mac-mac-studio-apple-m1-max',
    displayName: 'Mac Studio — Apple M1 Max',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/mac-studio-apple-m1-max',
    processorPaths: [],
    macPaths: ['/macs/mac-studio-apple-m1-max'],
    aliases: ['Apple M1 Max'],
    requiredConfiguration: {
      physicalCores: 10,
    },
  },
  {
    key: 'mac-mac-mini-late-2020',
    displayName: 'Mac mini (Late 2020) — Apple M1',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/mac-mini-late-2020',
    processorPaths: [],
    macPaths: ['/macs/mac-mini-late-2020'],
    aliases: ['Apple M1'],
    requiredConfiguration: {
      physicalCores: 8,
    },
  },
  {
    key: 'mac-imac-24-inch-mid-2021',
    displayName: 'iMac (24-inch Mid 2021) — Apple M1',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/imac-24-inch-mid-2021',
    processorPaths: [],
    macPaths: ['/macs/imac-24-inch-mid-2021'],
    aliases: ['Apple M1'],
    requiredConfiguration: {
      physicalCores: 8,
    },
  },
  {
    key: 'mac-imac-24-inch-mid-2021-apple-m1-3-2-ghz-8-cores',
    displayName: 'iMac (24-inch Mid 2021) — Apple M1',
    vendor: 'apple',
    architecture: 'arm',
    pageUrl: 'https://browser.geekbench.com/macs/imac-24-inch-mid-2021-apple-m1-3-2-ghz-8-cores',
    processorPaths: [],
    macPaths: ['/macs/imac-24-inch-mid-2021-apple-m1-3-2-ghz-8-cores'],
    aliases: ['Apple M1'],
    requiredConfiguration: {
      physicalCores: 8,
    },
  },
] as const;
